<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
?>
<?php

$productId = $this->getRequest ()->getParam ( 'id' );
$objectModelManager = \Magento\Framework\App\ObjectManager::getInstance ();
$isLinkEnabled = 0;
$sellerId = $objectModelManager->get ( 'Magento\Catalog\Model\Product' )->load ( $productId )->getSellerId ();
if (! empty ( $sellerId )) {
 $isLinkEnabled = $objectModelManager->get ( 'Apptha\Marketplace\Model\Seller' )->load ( $sellerId, 'customer_id' )->getShowProfile ();
}
if ($isLinkEnabled == 1) {
 $seller = $objectModelManager->get ( 'Apptha\Marketplace\Helper\Data' );
 $requestPath = $seller->getSellerRequestpath ( $productId );
 $sellerProfile = $seller->getSellerProfile ();
 if ($sellerProfile && $requestPath ['request_path'] != '') {
  ?>
<div class="linker_seller">
    <strong><?php echo __('SELLER'); ?></strong> <a
        href="<?php echo $block->getUrl($requestPath['request_path']);?>"
        class="link_seller">
            <?php echo ucfirst($requestPath['store_name']); ?></a>
</div>
<?php }
}?>