<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
?>
<?php

/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading"
            aria-level="2"><?php /* @escapeNotVerified */ echo __('Registered Sellers') ?></strong>
    </div>
    <div class="block-content"
        aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
            action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
            method="post" id="login-form"
            data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login"
                data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <div class="control">
                        <input name="login[username]"
                            value="<?php echo $block->escapeHtml($block->getUsername()) ?>"
                            <?php if ($block->isAutocompleteDisabled()) :?>
                            autocomplete="off" <?php endif; ?>
                            id="email" type="email" class="input-text"
                            title="<?php /* @escapeNotVerified */ echo __('Email') ?>"
                            data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password"
                            <?php if ($block->isAutocompleteDisabled()) :?>
                            autocomplete="off" <?php endif; ?>
                            class="input-text" id="pass"
                            title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                            data-validate="{required:true, 'validate-password':true}">
                    </div>
                </div>
                  <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit"
                            class="action login primary" name="send"
                            id="send2">
                            <span><?php /* @escapeNotVerified */ echo __('Login') ?></span>
                        </button>
                    </div>
                    <div class="secondary">
                        <a class="action remind"
                            href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>