<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
?>
<?php
$productId = $this->getRequest ()->getParam ( 'id' );
$objectModelManager = \Magento\Framework\App\ObjectManager::getInstance ();
$isLinkEnabled = 0;
$videoUrl = $objectModelManager->get ( 'Magento\Catalog\Model\Product' )->load ( $productId )->getVideoUrl ().'<br/>';
parse_str( parse_url( $videoUrl, PHP_URL_QUERY ), $my_array_of_vars );
$url = $my_array_of_vars['v'];
?>
<!--  <iframe src="https://www.youtube.com/embed/<?php //echo $url?>" frameborder="0" allowfullscreen></iframe> -->