<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
?>
<td>
<?php
/**
 *
 * Price fixed|Percent
 */
 $optionCount=$this->getData('optioncounts');
 $selectSubOptionCount=$this->getData('selectoption');
 $optionPriceTypeData=$this->getData('optionpricetypedata');
?>
<select  name="<?php
      $optionCountValue = $optionCount;
      echo 'product[options][' . $optionCountValue . '][values][' . $selectSubOptionCount . '][price_type]';
      ?>" id="<?php $optionCountValue = $optionCount; echo 'product_option_' . $optionCountValue . '_select_' . $selectSubOptionCount . '_price_type'; ?>"
                                class="select product-option-price-type"  title="">
                                    <option value="fixed"<?php
                                        if (isset ( $optionPriceTypeData ) && $optionPriceTypeData == 'fixed') {
                                            echo 'selected';
                                        } ?>><?php echo __('fixed'); ?></option>
                                    <option value="percent"<?php
                                        if (isset ( $optionPriceTypeData ) && $optionPriceTypeData == 'percent') {
                                            echo 'selected';
                                        }
                                ?>><?php echo __('Percent'); ?></option>
</select>
</td>