<?php
/**
 * Apptha
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 * ==============================================================
 * MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category Apptha
 * @package Apptha_Marketplace
 * @version 1.2
 * @author Apptha Team <developers@contus.in>
 * @copyright Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license http://www.apptha.com/LICENSE.txt
 */
?>
<?php
/**
 * Checking whether product add/edit
 */
$productId = $this->getRequest ()->getParam ( 'product_id' );
$name = $sku = $price = $description = $weight = $metakeyword = $metaDescription = $qty = $baseImage = $status = $specialPrice = $specialPriceFromDate = $specialPriceToDate = $type = $typeId = '';
$nationalShippingAmount = $internationalShippingAmount = '';
$isInStock = 1;
$productCategoryIds = $mediaGallery = array ();
if (! empty ( $productId )) {
    $productData = $block->getProductData ( $productId );
    $name = $productData->getName ();
    $sku = $productData->getSku ();
    $typeId = $productData->getTypeId ();
    $price = round ( $productData->getPrice (), 2 );
    $specialPrice = $productData->getSpecialPrice ();
    if ($specialPrice != '') {
        $specialPrice = round ( $productData->getSpecialPrice (), 2 );
    }
    $specialPriceFromDate = $productData->getSpecialFromDate ();
    $specialPriceToDate = $productData->getSpecialToDate ();
    if ($specialPriceFromDate != '') {
        $fromDate = new DateTime ( $specialPriceFromDate );
        $specialPriceFromDate = $fromDate->format ( 'm/d/Y ' );
    }
    if ($specialPriceToDate != '') {
        $toDate = new DateTime ( $specialPriceToDate );
        $specialPriceToDate = $toDate->format ( 'm/d/Y ' );
    }
    $description = $productData->getDescription ();
    $weight = round ( $productData->getWeight (), 2 );
    $productCategoryIds = $productData->getCategoryIds ();
    $stockData = $block->getProductStockDataQty ( $productId );
    $qty = $stockData->getQty ();
    $isInStock = $stockData->getIsInStock ();
    if (empty ( $isInStock )) {
        $isInStock = 0;
    }
    $mediaGallery = $productData->getMediaGallery ();
    $baseImage = $productData->getImage ();
    $status = $productData->getStatus ();
    $productApproval = $productData->getProductApproval ();
    $metakeyword = $productData->getMetaKeyword ();
    $metaDescription = $productData->getMetaDescription ();

    $nationalShippingAmount = $productData->getNationalShippingAmount ();
    $internationalShippingAmount = $productData->getInternationalShippingAmount ();
}
/**
 * Assigning product types
 */
$productTypesVal = $block->getProductTypes ();
$productTypes = explode ( ',', $productTypesVal );
/**
 * Setting weight flag for displaying weight field
 */
$weightFlag = 0;
if (in_array ( 'simple', $productTypes )) {
    $weightFlag = 1;
}
if (count ( $productTypes ) >= 1 && $productTypes [0] == 'virtual' || count ( $productTypes ) >= 1 && $productTypes [0] == 'downloadable') {
    $weightFlag = 0;
}
?>
<form class="form product form-product" action="<?php echo $block->getPostActionUrl() ?>" method="post"
    id="form_product_validate" enctype="multipart/form-data"
    autocomplete="off">
    <input type="hidden" id="current_product_id" value="<?php echo $productId; ?>" name="product_id" />
    <fieldset class="fieldset create info">
        <legend class="legend">
            <span><?php echo __('Product Details') ?></span>
        </legend>
        <br>
        <div class="field required">
        <input type="hidden" value="<?php echo $this->getRequest ()->getParam ( 'config' ) == '1'?$this->getRequest ()->getParam ( 'config' ):""?>"  name="config" />
            <div
                <?php if(!empty($productId)){ echo 'style="display:none;"'; } ?>>
                <label for="name" class="label label-attribute"><span><?php echo __('Attribute Set'); ?></span></label>
                <div class="control control-attribute">
                <?php if (! empty ( $productId ) && $typeId == 'configurable') {?>
                <input type="hidden" value="<?php echo $productData->getAttributeSetId(); ?>"  name="set" />
                <?php } ?>
                <select id="attribute_set" <?php if(!empty($productId)){ echo 'disabled'; } ?>  name="set" 
                        title="<?php echo __('Attribute Set') ?>" class="validate-select" data-validate="{required:true}">
                        <option  value="<?php echo $block->getDefaultAttributeSetId(); ?>"><?php echo __('Default'); ?></option>
                    <?php
                    $attributeSet = $block->getAttributeSet ();
                    foreach ( $attributeSet as $set ) {
                        if ($set ['label'] != 'Default') {
                      ?>
                    <option value="<?php echo $set['value']; ?>"><?php echo $set['label']; ?></option>
                    <?php }
                    }
                    ?>
                </select>
          </div>
<?php if($typeId == 'configurable'){ ?>
<input type="hidden" value="<?php echo $typeId; ?>" name="type" />
<?php } ?>
<label for="type" class="label"><span><?php echo __('Product Type'); ?></span></label>
                <div class="control control-prototype">
                    <select id="product_type" <?php if(!empty($productId)){ echo 'disabled'; } ?>
                        name="type"<?php if(!empty($productId)){ echo __('disabled'); } ?>  title="<?php echo __('Product Type') ?>"
                        class="validate-select" data-validate="{required:true}">
                        <?php
                        foreach ( $productTypes as $typeVal ) {
                         $typeLabel = ucfirst ( $typeVal );
                         ?>
                            <option value="<?php echo $typeVal; ?>"><?php echo __($typeLabel); ?></option>
                            <?php } ?>
                            </select>
                </div>
            </div>
<?php
/**
 * Get categories
 */
$categories = $block->getStoreCategories ( true, false, true );
?>
<div class="fieldset marketplace-category-type">
                <label for="category" class="label category-label"><span><?php echo __('Product Categories'); ?></span></label>
                <div class="block-category">
                <?php
                /**
                 * Check the Categories is not equal to empty
                 */
                if (! empty ( $categories )) {
                 echo $block->alphabaticalOrder ( $categories, $productCategoryIds );
                }
                ?>
            </div>
            </div>
            <label for="name" class="label"><span><?php echo __('Name') ?></span></label>
            <div class="control">
                <input type="text" name="product[name]" id="name"  value="<?php echo $name; ?>"  title="<?php echo __('Name') ?>" class="input-text" data-validate="{required:true}">
            </div>
            <label for="sku" class="label"><span><?php echo __('SKU') ?></span></label>
            <div class="control">
                <input type="text" name="product[sku]" id="sku" value="<?php echo $sku; ?>"
                    title="<?php echo __('SKU') ?>" class="input-text"  data-validate="{required:true}">
                    <input   type="hidden" id="currentsku"  value="<?php echo $sku;?>" />
                <div for="sku" generated="true" class="available name-error" id="name-error"></div>
                <div class="sku-update-loader cssload-jumping">
                    <span></span><span></span><span></span><span></span><span></span>
                </div>
                <input type="hidden" id="sku_successmessage"  value="<?php echo __('SKU is available');?>" />
                <input type="hidden" id="sku_errormessage" value="<?php echo __('SKU is not available');?>" />
            </div>
           <label for="price" class="label"
                <?php if($typeId == 'configurable'){ echo 'style="display:none;"'; } ?>><span><?php echo __('Price') ?></span></label>
            <div class="control"
                <?php if($typeId == 'configurable'){ echo 'style="display:none;"'; } ?>>
                <input type="text" name="product[price]" id="price"
                    value="<?php echo $price; ?>"
                    title="<?php echo __('Price') ?>" class="input-text"
                    data-validate="{required:true,'validate-greater-than-zero':true}"
                    <?php if($typeId == 'configurable'){ echo 'disabled="disabled"'; } ?>>
                <strong>[<?php echo $block->getBaseCurrency(); ?>]</strong>
            </div>
            <div class="field" id="special_price_section">
                <label for="specialprice" class="label"><span><?php echo __('Special Price') ?></span></label>
                <div class="control">
                <input type="text" name="product[specialprice]"
                        id="specialprice"  value="<?php echo $specialPrice; ?>"
                        title="<?php echo __('Special Price') ?>"   data-validate="{'validate-greater-than-zero':true}"
                        class="input-text"> <strong>[<?php echo $block->getBaseCurrency(); ?>]</strong>
                </div>

                <div id="date_range">
                    <label for="specialpricefromdate"><span><?php echo __('Special Price From Date') ?>:</span></label>
                    <div class="control">
                        <input class="input-text " type="text"
                            id="specialpricefromdate"
                            name="product[specialpricefromdate]"
                            value="<?php echo $specialPriceFromDate;?>" />
                    </div>
                    <label for="specialpricetodate"><span><?php echo __('Special Price To Date') ?>:</span></label>
                    <div class="control">
                        <input class="input-text " type="text"
                            id="specialpricetodate"  name="product[specialpricetodate]"  value="<?php echo $specialPriceToDate;?>" />
                    </div>
                </div>
            </div>
            <div class="stock-description">
                <label for="tax_class_id" class="label"><span><?php echo __('Description') ?></span></label>
                <textarea id="description" name="product[description]"
                    rows="2" cols="15"><?php echo $description; ?></textarea>
            </div>
            <div class="qty-stock">
                <div><label for="qty" class="label"><span><?php echo __('Quantity') ?></span><em style="color: red; font-weight: normal; font-family: 'Open Sans', sans-serif; font-size: 12px;">*</em></label>
<div class="qty-input-alert"><?php if($typeId != 'configurable'){ ?>
<input type="text" name="product[quantity_and_stock_status][qty]"
id="qty" value="<?php echo $qty; ?>"
title="<?php echo __('Quantity') ?>"
class="input-text downloadable-quantity"
data-validate="{'required':true,'validate-number':true}">
<?php } ?></div></div>
<div>
 <select id="quantity_and_stock_status"
                    name="product[quantity_and_stock_status][is_in_stock]"
                    title="<?php echo __('Tax Class') ?>"
                    class="validate-select">
                    <option value="1" <?php if ($isInStock == 1 || empty ( $isInStock )) {
                         echo 'selected="selected"';
                        }
                        ?>><?php echo __('In Stock'); ?></option>
                    <option
                        <?php    if ($isInStock == 0) {
                         echo 'selected="selected"';
                        }
                        ?>
                        value="0"><?php echo __('Out of Stock'); ?></option>
                </select></div>
<?php
$isSellerProductShipping = $this->isSellerProductShipping ();
if ($isSellerProductShipping == 1) {
 ?></div>

            <div>
                <label for="national_shipping_amount" class="label"><span><?php echo __('National Shipping Amount') ?></span><em
                    style="color: red; font-weight: normal; font-family: 'Open Sans', sans-serif; font-size: 12px;">*</em></label>
                <input type="text" name="national_shipping_amount"
                    id="national_shipping_amount"  value="<?php echo $nationalShippingAmount; ?>"  title="<?php echo __('National Shipping Amount') ?>"  class="input-text"
                    data-validate="{required:true,'validate-greater-than-zero':true}">
            </div>
            <div>
                <label for="international_shipping_amount" class="label"><span><?php echo __('International Shipping Price') ?></span><em
                    style="color: red; font-weight: normal; font-family: 'Open Sans', sans-serif; font-size: 12px;">*</em></label>
                <input type="text" name="international_shipping_amount"  id="international_shipping_amount" value="<?php echo $internationalShippingAmount; ?>"   title="<?php echo __('International Shipping Amount') ?>"
                    class="input-text"   data-validate="{required:true,'validate-greater-than-zero':true}">

<?php  } ?>
</div>
            <div id="weight_container"
                <?php if($weightFlag != 1){ echo 'style="display:none;"'; } ?>>
                <label for="weight" class="label"><span><?php echo __('Weight') ?></span></label>
                <input class="weight-input validate-number" id="weight"  <?php if($weightFlag != 1){ echo 'disabled'; } ?>
                    name="product[weight]"   value="<?php echo $weight; ?>" type="text"> <span><?php echo __('lbs');?></span>
            </div>
        </div>
    </fieldset>
    <div id="uploaded_images_for_product"></div>
    <div id="remove_images_for_product"></div>
    <div id="configurable_content_form"></div>
    <div id="base_image_for_product" style="display: none;">
<?php if(!empty($baseImage)){ ?>
<input class="base_image" type="radio" name="base_image"
            title="<?php echo __('base'); ?>"
            value="<?php echo $baseImage; ?>">
<?php } ?>
</div>
<?php
$productAutoApproval = $block->getProductApproval ();
?>
<div class="product_status"
        <?php
        if (empty ( $productId ) && ($productAutoApproval == 0)) {
         echo __ ( 'style="display:none;"' );
        } elseif (! empty ( $productId ) && ($productApproval == 1)) {
         echo __ ( 'style="display:block;"' );
        }
        ?>>
        <label for="status" class="label"><span><?php echo __('Product Status') ?></span></label>
        <select id="status" name="product[status]"
            title="<?php echo __('Enable Product') ?>"
            class="validate-select">
            <option value="1" <?php if($status == 1){ echo 'selected="selected"'; } ?>><?php echo __('Enable'); ?></option>
            <option value="2"<?php if($status == 2){ echo 'selected="selected"'; } ?>><?php echo __('Disable'); ?></option>
        </select>
    </div>
    <div class="fields">
        <div class="field meta_keyword ">
            <label for="meta_keyword" class="label"><span><?php  echo __('Meta Keywords') ?></span></label>
            <textarea id="product_meta_keyword"   name="product[meta_keyword]" rows="5" cols="60" class="input-text ">
     <?php echo $metakeyword;?>
     </textarea>
        </div>
    </div>
    <div class="fields">
        <div class="field meta_description ">
            <label for="meta_description" class="label"><span><?php  echo __('Meta Description') ?></span></label>
            <textarea id="product_meta_description"
                name="product[meta_description]" rows="5" cols="60"
                class="input-text ">
    <?php echo $metaDescription;?>
    </textarea>
        </div>
    </div>
    <input type="hidden" id="sku_validate_url" name="sku_validate_url"
        value="<?php echo $block->getSkuValidateAjaxUrl(); ?>" />
    <script>
       require([
                "jquery",
                "mage/calendar"
            ], function($){

               $("#date_range").dateRange({
                 buttonText:"<?php echo __('Select Date') ?>",
                    from:{
                        id:"specialpricefromdate"
                    },
                    to:{
                        id:"specialpricetodate"
                    }
               });
            });
        </script>
 <!-- Marketplace custom attribute section -->
<?php
$customAttributes = $block->geCustomAttributes ();
if ($customAttributes == 1) {
 ?>
<input type="hidden"  value="<?php echo $block->getCustomAttributesUrl(); ?>"  name="custom_attributes_ajax_url"  id="custom_attributes_ajax_url" />
    <div id="custom_attributes_loader" style="display: none;">...</div>
    <div id="custom_attributes"></div>
    <script>
require([
         'jquery',
         'mage/calendar'
     ], function($){
        $('#attribute_set').on('change', function(e) {
            $('#custom_attributes_loader').show();
            var customAttributeSetId = $('#attribute_set').val();
            var currentProductId = $('#current_product_id').val();
            $.ajax({
                type: "POST",
                url: $('#custom_attributes_ajax_url').val(),
                 data: {custom_attribute_set_id: customAttributeSetId,current_product_id: currentProductId},
                success: function(transport){
                $('#custom_attributes').html(transport);
                $('#custom_attributes_loader').hide();
                }
                });
        });
    // Update custom attributes
    $( document ).ready(function(){
        var customAttributeSetId = $('#attribute_set').val();
        var customCurrentProductId = $('#current_product_id').val();
        $('#custom_attributes_loader').show();
        $.ajax({
            type: "POST",
            url: $('#custom_attributes_ajax_url').val(),
             data: {custom_attribute_set_id: customAttributeSetId,current_product_id: customCurrentProductId},
             success: function(transport){
                $('#custom_attributes').html(transport);
                $('#custom_attributes_loader').hide();
                $(".calendar_inputField").calendar({
                    buttonText:"<?php echo __('Select Date') ?>",
               });
            }
            });
    });
});
</script>
<?php } ?>
<?php echo $this->getChildHtml('marketplace_product_customoptions_js');?>
<?php if($productId != ''){?>
<?php echo $this->getChildHtml('marketplace_product_downloadable_edit');?>
<?php } else { ?>
<?php echo $this->getChildHtml('marketplace_product_downloadable');?>
<?php }?>
<?php echo $this->getChildHtml('marketplace_product_video_add');?>
</form>
<input type="hidden"  value="<?php echo $block->getCategoryTreeAjaxUrl(); ?>"  name="category_tree_ajax_url" id="category_tree_ajax_url" />
<script>
require([
    'jquery',
    'mage/adminhtml/wysiwyg/tiny_mce/setup'
], function(jQuery){
var config = '',
    editor;
jQuery.extend(config, {
    settings: {
        theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,' +
            'fontselect,fontsizeselect,|,forecolor,backcolor,|,link,unlink,image,|,bullist,numlist,|,code',
        theme_advanced_buttons2: null,
        theme_advanced_buttons3: null,
        theme_advanced_buttons4: null,
        theme_advanced_statusbar_location: null
    },
    files_browser_window_url: false
});
editor = new tinyMceWysiwygSetup(
    'description',
    config
);
editor.turnOn();
jQuery('#description')
    .addClass('wysiwyg-editor')
    .data(
        'wysiwygEditor',
        editor
    );});
</script>
<script>
require([
    'jquery',
    'mage/mage'
], function($){
$('.sku-update-loader').hide();
var selectedCatIds = '<?php echo json_encode($productCategoryIds); ?>';
var usedCat = [];
    var dataForm = $('#form_product_validate');
    var ignore = null;
    var productsku;
    var skuAvailableFlag;
    dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');
    <?php $categoryid = array(); ?>
    <!-- Category child node show/hide -->
    $('.block-category li.parent > a span').click(function () {
    $(document.body).on("click",".block-category li.parent > a span",function(e){
    e.stopImmediatePropagation();
            var catId = $(this).closest("li").attr("id");
           $(this).removeClass("end-plus");
           var currentId = $(this).attr('id');
             if(usedCat.indexOf(catId) === -1) {
                 usedCat.push(catId);
         $('#'+catId).append('<div class="category-update-loader">...</div>');
                $.ajax({
                    type: "POST",
                    url: $('#category_tree_ajax_url').val(),
                    data: {category_id: catId,selectedCatIds:selectedCatIds},
                    success: function(transport){
                    $('#'+catId+' .category-update-loader').remove();
                    $('#'+currentId).addClass("end-minus");
                    $('#'+catId).append(transport);
                    }
                    });
            e.preventDefault();
            }else{
            $(this).toggleClass('end-minus end-plus');
            $('#'+catId+' li').toggle();
            }
        });
    });

    $("#image_upload_form").on('submit',(function(e){
        e.preventDefault();
           var imgVal = $('#upload_product_images').val();
           if(imgVal != ''){
            $('#image_upload_ajax_loader').show();
            $.ajax({
                url: $('#image_upload_ajax_url').val(),
                type: 'POST',
                success: function (transport) {
                $('#image_upload_ajax_loader').hide();
                $('#images_list').append(transport);
                $('#upload_product_images').val('');
                },
                data: new FormData(this),
                cache: false,
                contentType: false,
                processData: false
            });
        }
        }));
    $("#upload_product_images").change(function() {
    $('#image_upload_form').submit();
    });
    $('#images_list').on('click', '.image_close', function(e) {
    $(this).parents("span:first").remove();
    radiovalidate();
    });
    $('#form_product_validate').on('submit', function() {
    $('#uploaded_videos_for_product').append($(this).clone());
    if($('#form_product_validate').valid()){
    $("#btn_save_product").attr('disabled','disabled');
    $( ".hidden_uploaded_image_path" ).each(function( index ) {
    $('#uploaded_images_for_product').append($(this).clone());
    });
    var configurableRedirectFlag = 0;
    var configurableRedirectFlag = 0;
    var productTypeFlagForConfigurable = $('#product_type').val();
    var isConfigurableFlagForConfigurable = $('#is_configurable_product').val();
    var configurableProductFlagCheck = 0;
    if(productTypeFlagForConfigurable == 'configurable' || isConfigurableFlagForConfigurable == 1){
    configurableProductFlagCheck = 1;
    }
    var configurableAssociatedProductFlag = 0;
    if($('#configurable_associated_product_flag')){
    var configurableAssociatedProductFlag = $('#configurable_associated_product_flag').val();
    }
    if(configurableProductFlagCheck == 1){
    if($('#variants_generate_flag').val() != 1){
    if(configurableAssociatedProductFlag != 1){
    $('#configurable_variant_error').show();
    $('#btn_save_product').removeAttr('disabled');
    return false;
    }
    }
    }
var configurableProductClone = $('#configurable_section_content_form').html();
$('#configurable_content_form').html('');
    $('#configurable_content_form').html(configurableProductClone);
    }
    });
    $('.remove_image_container').on('click', function(e) {
    $('#remove_images_for_product').append($(this).find('.remove_image').clone());
    });
    $('#images_list').on('click', '.base_image_container', function(e) {
    $('#base_image_for_product').html($(this).find('.base_image').clone());
    });
    $( document ).on('click','#btn_save_product', function() {
        productskuVal = $('#sku').val(); $("#selectBaseImage").hide();
        currentskuVal = $('#currentsku').val();
var getSelect = $("input:radio[name='base_image']:checked").val();
var imageLength = $("span[class='image_close']").length;
if((!getSelect || getSelect == 'undefined') && imageLength){
$("#selectBaseImage").show();return false;
}
        if(skuAvailableFlag == 0 && skuEnterFlag == 1 || productskuVal == currentskuVal){
        $('#form_product_validate').submit();
            }else{
            $('#sku').focus();
            return false;
            }
    });
    $("#product_type").change(function() {
    if($(this).val() == 'virtual'){
    $("#weight_container").hide();
    $("#weight").attr("disabled",true);
    }else{
    $("#weight_container").show();
    $("#weight").attr("disabled",false);
    }
    });

    $("#product_type").change(function() {
        if($(this).val() == 'configurable'){
        $("#notify_stock_qty_label").hide();
        $("#notify_stock_qty").hide();
        }else{
        $("#notify_stock_qty_label").show();
        $("#notify_stock_qty").show();
        }
        });
  var skuAvailableFlag=0;
  var skuEnterFlag = 0;

  $('#sku').blur(function(){
  skuEnterFlag = 1;
  });
    $('#sku').keyup(function(){
    skuAvailableFlag = 1;
    $('.sku-update-loader').show();
        productsku= $('#sku').val();
        currentsku=$('#currentsku').val();
        if(productsku.length!==0){
          $('#sku').removeClass("mage-error");
          $('#sku-error').css("display", "none");
           if(currentsku!=productsku  ){
           $.ajax({
            type: "POST",
            url: $('#sku_validate_url').val(),
            data: {sku: productsku},
            success: function(transport){
              if(transport==0){
                $('.available').html($('#sku_successmessage').val());
                $('.available').css("color", "green");
                $('.available').css("font-size", "1.2rem");
                skuAvailableFlag=0;
                $("#btn_save_product").prop("disabled", false);
               }
             else{
               $('.available').html($('#sku_errormessage').val());
               $('.available').css("color", "#e02b27");
               $('.available').css("font-size", "1.2rem");
               $('#sku').addClass("mage-error");
               skuAvailableFlag=1;
              }
              $('.sku-update-loader').hide();
           }
            });
    }
        }
    if(currentsku==productsku){
     $('.available').css("display", "none");
     $('.sku-update-loader').hide();
    }
    else if(productsku.length==0){
     $('.available').css("display", "none");
     $('.sku-update-loader').hide();

    }
    else{
    $('.available').css("display", "block");
    }
  });
});
</script>
<form action="<?php echo $block->getImageUploadAjaxUrl(); ?>"
    method="POST" enctype="multipart/form-data"
    class="image_upload_form" id="image_upload_form">
    <input type="hidden" id="image_upload_ajax_url" class="images_list"
        name="image_upload_ajax_url"
        value="<?php echo $block->getImageUploadAjaxUrl(); ?>" /> <label
        for="upload_product_images" class="label"><span><?php echo __('Images') ?></span></label>
    <div id="images_list" class="images_list">
        <div class="image_holder image-placeholder">
            <input type="file" name="product_images[]"
                id="upload_product_images" multiple>
            <p class="image-placeholder-text"><?php echo __('Click here to add images.'); ?></p>
        </div>
  <?php
  if (! empty ( $productId )) {
   $baseImageName = '';
   $mediaImageUrl = $block->getMediaImageUrl ();
   if (! empty ( $baseImage )) {
    $baseImageNameArr = explode ( '.', $baseImage );
    $baseImageName = $baseImageNameArr [0];
   }
   foreach ( $mediaGallery ['images'] as $image ) {
    if ($image ['media_type'] == 'image' && ! empty ( $baseImageName )) {
     $imagePath = $image ['file'];
     ?>
 <span> <span class="image_close remove_image_container">x <input
                type="hidden" class="remove_image" name="remove_image[]"
                value="<?php echo $image['value_id']; ?>">
        </span> <span class="base_image_container"> <input
                class="base_image" type="radio"
                <?php
     if (strpos ( $imagePath, $baseImageName ) !== false || $baseImage == $imagePath) {
                echo 'checked="checked"';
            }
            ?>
                name="base_image" title="<?php echo __('base'); ?>"
                value="<?php echo $imagePath; ?>">
        </span> <img class="base_image_section"
            src="<?php echo $mediaImageUrl.DIRECTORY_SEPARATOR.$imagePath; ?>"
            alt="<?php echo $imagePath; ?>" height="200" width="200">
        </span>
  <?php
        }
    }
}
?>
<div for="selectBaseImage" generated="true" class="mage-error" id="selectBaseImage" style="display: none;"><?php echo __('Please select base image for your product'); ?></div>
 </div>
    <div class="cssload-jumping" id="image_upload_ajax_loader"
        style="display: none;">
        <span></span><span></span><span></span><span></span><span></span>
    </div>
    <input style="display: none;" type="submit" value="submit">
</form>
<span class="magenote"><?php echo __('Note: Please add images with same height and width for better visibility.'); ?></span>
<!-- Product custom option and dynamically add downloadable product data -->
<script type="text/javascript">
function removeMarketPlaceCustomOption(value) {
    value.up('div').remove();
}
function changeMarketPlaceCustomOption(value, option_value) {
    var child_html;
    var child_custom_option_value = value.getValue();
    switch (child_custom_option_value) {
        case "drop_down":
        case "radio":
        case "checkbox":
        case "multiple":
            child_html = $("product_option_CCC_type_select").innerHTML.replace(/CCC/g, option_value);
            break;
        case "field":
        case "area":
            child_html = $("product_option_CCC_type_text").innerHTML.replace(/CCC/g, option_value);
            break;
        case "date":
        case "date_time":
        case "time":
            child_html = $("product_option_CCC_type_date").innerHTML.replace(/CCC/g, option_value);
            break;
        case "file":
            child_html = $("product_option_CCC_type_file").innerHTML.replace(/CCC/g, option_value);
            break;
        default :
            child_html = $("product_option_CCC_type_text").innerHTML.replace(/CCC/g, option_value);
    }
    if (value.up('table').nextSiblings('table') != '')
    {
        value.up('table').next('table').remove();
        value.up('div').insert(child_html);
    }
    else
    {
        value.up('div').insert(child_html);
    }
}
function removeMarketPlaceChildSelectOption(value) {
    value.up('tr').remove();
}
function addMarketPlaceChildSelectOption(value, sub_option_value) {
    var selectChildCustomOption = $("product_option_CCC_select_AAA").innerHTML.replace(/CCC/g, sub_option_value);
    var new_selectChildCustomOption = selectChildCustomOption.replace(/AAA/g, selectSubChildCustomOptionCount);
    $(value).insert(new_selectChildCustomOption);
    selectSubChildCustomOptionCount = selectSubChildCustomOptionCount + 1;
}
</script>
<!-- Following div dynamically create custom options  -->
<div class="hidden-custom-option" style="display: none;">
    <div class="option-box" id="marketplace_custom_option_YYY">
        <!-- Div for removing custom option -->
        <div class="dont-remove market_place_option-box">
            <!-- Product custom option table -->
            <table id="product_option_XXX"
                class="option-header form-list" cellpadding="0"
                cellspacing="0">
                <input type="hidden" id="product_option_XXX_is_delete"
                    name="product[options][XXX][is_delete]" value="">
                <input type="hidden"   id="product_option_XXX_previous_type"  name="product[options][XXX][previous_type]" value="">
                <input type="hidden"    id="product_option_XXX_previous_group"  name="product[options][XXX][previous_group]"   value="">
                <input type="hidden" id="product_option_XXX_id"   name="product[options][XXX][id]" value="XXX">
                <input type="hidden" id="product_option_XXX_option_id" name="product[options][XXX][option_id]" value="0">
                <thead>
                    <tr>
                        <th class="opt-title"><label class="required"><em>*</em> <?php echo __('Title'); ?></label>
                        </th>
                        <th class="opt-type"><label class="required"><em>*</em> <?php echo __('Input Type'); ?></label></th>
                        <th class="opt-req"><label><?php echo __('Is Required'); ?></label></th>
                        <th class="a-right">
                        <button id="delete_product_option_XXX" title="<?php echo __('Delete Option'); ?>"   type="button"
                                class="button scalable delete delete-product-option " onclick="removeMarketPlaceCustomOption(this)">
                                <span><span><?php echo __('Delete Option'); ?></span></span>
                            </button></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><input type="text"
                            class="required-entry input-text"
                            id="product_option_XXX_title"
                            name="product[options][XXX][title]" value=""></td>
                        <td><select
                            onchange="changeMarketPlaceCustomOption(this, XXX)"
                            name="product[options][XXX][type]"
                            id="product_option_XXX_type"
                            class="select validate-select" title="">
                                <option value="">-- <?php echo __('Please select'); ?> --</option>
                                <optgroup
                                    label="<?php echo __('Text'); ?>">
                                    <option value="field"><?php echo __('Field'); ?></option>
                                    <option value="area"><?php echo __('Area'); ?></option>
                                </optgroup>
                                <optgroup
                                    label="<?php echo __('File'); ?>">
                                    <option value="file"><?php echo __('File'); ?></option>
                                </optgroup>
                                <optgroup
                                    label="<?php echo __('Select'); ?>">
                                    <option value="drop_down"><?php echo __('Drop-down'); ?></option>
                                    <option value="radio"><?php echo __('Radio Buttons'); ?></option>
                                    <option value="checkbox"><?php echo __('Checkbox'); ?></option>
                                    <option value="multiple"><?php echo __('Multiple Select'); ?></option>
                                </optgroup>
                                <optgroup
                                    label="<?php echo __('Date'); ?>">
                                    <option value="date"><?php echo __('Date'); ?></option>
                                    <option value="date_time"><?php echo __('Date'); ?> &amp; <?php
        echo __ ( 'Time' );
        ?></option>
                                    <option value="time"><?php echo __('Time'); ?></option>
                                </optgroup>
                        </select></td>
                        <td class="opt-req"><select
                            name="product[options][XXX][is_require]"
                            id="product_option_XXX_is_require"
                            class="select" title="">
                                <option value="1"><?php echo __('Yes'); ?></option>
                                <option value="0"><?php echo __('No'); ?></option>
                        </select></td>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <!-- Product custom option text -->
    <div id="product_option_CCC_type_text" class="grid tier form-list">
        <table class="form-list border custom_option_text_field"
            cellpadding="0" cellspacing="0">
            <tbody>
                <tr class="headings">
<?php
/**
 * Product custom option title.
 * Price
 * Price type
 * SKU
 * Max characters.
 */
?>
                    <th class="type-price">
                    <label><?php echo __('Price'); ?></label>
                    </th>
                    <th class="type-type">
                    <label><?php echo __('Price Type'); ?></label>
                    </th>
                    <th class="type-sku">
                    <label><?php echo __('SKU'); ?></label>
                    </th>
                    <th class="type-last last">
                    <label><?php echo __('Max Characters'); ?></label>
                    </th>
                </tr>
                <tr>
                    <td>
                    <input type="text"  class="input-text validate-number product-option-price product-custom-option-price-val"
                        id="product_option_CCC_price" name="product[options][CCC][price]" value=""></td>
                    <td><select name="product[options][CCC][price_type]"  id="product_option_CCC_price_type" class="select product-option-price-type"  title="">
                            <option value="fixed"><?php echo __('fixed'); ?></option>
                            <option value="percent"><?php echo __('Percent'); ?></option>
                    </select></td>
                    <td><input type="text" class="input-text"   name="product[options][CCC][sku]" value=""></td>
                    <td class="type-last last"><input type="text"  class="input-text validate-zero-or-greater"  name="product[options][CCC][max_characters]" value=""></td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- Product custom option file -->
    <div id="product_option_CCC_type_file" class="grid tier">
        <table class="border form-list mareket_place_price_table"
            cellpadding="0" cellspacing="0">
            <tbody>
                <tr class="headings">
                    <th class="type-price"><label><?php echo __('Price'); ?></label></th>
                    <th class="type-type"><label><?php echo __('Price Type'); ?></label></th>
                    <th class="type-sku"><label><?php echo __('SKU'); ?></label></th>
                    <th class="type-title"><label><?php echo __('Allowed File Extensions'); ?></label></th>
                    <th class="last"><label><?php echo __('Maximum Image Size'); ?></label></th>
                </tr>
                <tr>
                    <td><input
                        class="input-text validate-zero-or-greater"
                        type="text" name="product[options][CCC][price]"
                        value=""></td>
                    <td><select name="product[options][CCC][price_type]"
                        id="product_option_CCC_price_type"
                        class="select product-option-price-type"
                        title="">
                            <option value="fixed"><?php echo __('fixed'); ?></option>
                            <option value="percent"><?php echo __('Percent'); ?></option>
                    </select></td>
                    <td><input type="text" class="input-text"
                        name="product[options][CCC][sku]" value=""></td>
                    <td><input class="input-text" type="text"
                        name="product[options][CCC][file_extension]"
                        value=""></td>
                    <td class="type-last last" nowrap=""><input
                        class="input-text" type="text"
                        name="product[options][CCC][image_size_x]"
                        value=""><?php echo __('x'); ?>&nbsp;
<input class="input-text" type="text"
                        name="product[options][CCC][image_size_y]"
                        value=""><?php echo __('px') . '.'; ?>
<br><?php echo __('leave blank if its not an image'); ?>
                </td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- Product custom option date -->
    <div id="product_option_CCC_type_date" class="grid tier form-list"
        style="">
        <table class="border form-list mareket_place_date_table"
            cellpadding="0" cellspacing="0">
            <tbody>
                <tr class="headings">
                    <th class="type-price"><label><?php echo __('Price'); ?></label></th>
                    <th class="type-type"><label><?php echo __('Price Type'); ?></label></th>
                    <th class="last"><label><?php echo __('SKU'); ?></label></th>
                </tr>
                <tr>
                    <td><input type="text"
                        class="input-text validate-number product-option-price product-option-price-val-data"
                        id="product_option_CCC_price"
                        name="product[options][CCC][price]" value=""></td>
                    <td><select name="product[options][CCC][price_type]"
                        id="product_option_CCC_price_type"
                        class="select product-option-price-type"
                        title="">
                            <option value="fixed"><?php echo __('fixed'); ?></option>
                            <option value="percent"><?php echo __('Percent'); ?></option>
                    </select></td>
                    <td class="last"><input type="text"
                        class="input-text type-sku"
                        name="product[options][CCC][sku]" value=""></td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- Product custom option select -->
    <div id="product_option_CCC_type_select" class="grid tier form-list">
        <table class="border market_place_dropdown_row form-list"
            cellpadding="0" cellspacing="0">
            <input type="hidden"
                class="required-option-select-type-rows"
                name="validation_CCC_result" value="">
            <thead>
                <tr class="headings">
                    <th class="type-title"><label class="required"> <em>*</em> <?php echo __('Title'); ?> </label></th>
                    <th class="type-price"><label><?php echo __('Price'); ?></label></th>
                    <th class="type-type"><label><?php echo __('Price Type'); ?></label></th>
                    <th class="type-sku"><label><?php echo __('SKU'); ?></label></th>
                    <th class="type-order"><label><?php echo __('Sort Order'); ?></label></th>
                    <th class="type-butt last">&nbsp;</th>
                </tr>
            </thead>
            <tbody id="select_option_type_row_CCC">
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="100" class="a-right">
                        <button id="add_select_row_button_CCC"
                            name="select_option_type_row_CCC"
                            title="<?php echo __('Add New Row'); ?>"
                            type="button"
                            class="button scalable add add-select-row"
                            onclick="addMarketPlaceChildSelectOption(this.name, CCC)">
                            <span><span><?php echo __('Add New Row'); ?></span></span>
                        </button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- Product custom option select add row -->
    <table>
        <tr id="product_option_CCC_select_AAA">
            <td>
               <input type="hidden"  name="product[options][CCC][values][AAA][option_type_id]" value="-1"> <input type="hidden"  id="product_option_CCC_select_AAA_is_delete"
                name="product[options][CCC][values][AAA][is_delete]" value="">
                <input type="text" class="required-entry input-text select-type-title" id="product_option_CCC_select_AAA_title" name="product[options][CCC][values][AAA][title]" value=""></td>
            <td>
            <input type="text" class="input-text validate-number product-option-price" id="product_option_CCC_select_AAA_price"
                name="product[options][CCC][values][AAA][price]" value=""></td>
            <td>
            <select name="product[options][CCC][values][AAA][price_type]"
                id="product_option_CCC_select_AAA_price_type"
                class="select product-option-price-type" title="">
                    <option value="fixed"><?php echo __('fixed'); ?></option>
                    <option value="percent"><?php echo __('Percent'); ?></option>
            </select>
            </td>
            <td><input type="text" class="input-text"  name="product[options][CCC][values][AAA][sku]" value=""></td>
            <td><input type="text"  class="validate-zero-or-greater input-text" name="product[options][CCC][values][AAA][sort_order]" value=""></td>
            <td class="last"><span title="Delete row">
                    <button id="delete_select_row_button"  title="Delete Row" type="button" class="button delete_select_row_button scalable delete delete-select-row icon-btn"
                        onclick="removeMarketPlaceChildSelectOption(this)" style="">
                        <span> <span><?php echo __('Delete Row'); ?></span></span>
                    </button>
            </span></td>
        </tr>
    </table>
</div>
<?php echo $this->getChildHtml('marketplace_product_downloadable_additional');?>