<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?>
<?php
/**
 * Checking whether product add/edit
 */
$productId = $this->getRequest ()->getParam ( 'id' );
$nationalShippingAmount = $internationalShippingAmount = '';
?>
<form class="form product form-product"
    action="<?php echo $block->getSaveAssignProductUrl() ?>"
    method="post" id="add_assign_product" enctype="multipart/form-data"
    autocomplete="off">
    <input type="hidden" name="product_id" />
    <fieldset class="fieldset create info">
        <legend class="legend">
            <span><?php echo __('Product Details') ?></span>
        </legend>
        <br>
        <div class="field required">
<?php
/**
 * To add Sku for Product
 * Field:Sku
 */
?>
<input type="hidden" id="assign-product-id"  name="assignproduct[assign_product_id]"  value="<?php echo $productId; ?>" /> 
<label for="sku"  class="label"><span><?php echo __('SKU') ?></span></label>
            <div class="control"> 
            <input type="text" name="assignproduct[sku]" id="product_sku" title="<?php echo __('SKU') ?>" class="input-text" data-validate="{required:true}">
                <input type="hidden" id="currentsku" />
                <div for="sku" generated="true" class="availablesku name-error" id="name-error"></div>
                <div class="sku-update-loader cssload-jumping">
                    <span></span><span></span><span></span><span></span><span></span>
                </div>
                <input type="hidden" id="sku_successmessage"  value="<?php echo __('SKU is available');?>" /> 
                <input  type="hidden" id="sku_errormessage"   value="<?php echo __('SKU is not available');?>" />
            </div>
<?php
/**
 * To add Price for Product
 * Field:price
 */
?>
<label for="price" class="label"><span><?php echo __('Price') ?></span></label>
            <div class="control">
                <input type="text" name="assignproduct[price]" id="product_price" value=""
                    title="<?php echo __('Price') ?>" class="input-text" data-validate="{required:true,'validate-greater-than-zero':true}">
            </div>
<?php
/**
 * To add stock data for Product
 * Field:qty,is in stock
 */
?>
    <label for="qty" class="label"><span><?php echo __('Quantity') ?></span></label>
            <div class="control">
                <input type="text"
                    name="assignproduct[quantity_and_stock_status][qty]"
                    id="product_qty"
                    title="<?php echo __('Quantity') ?>"
                    class="input-text"
                    data-validate="{'required':true,'validate-number':true}">
            </div>
<?php
/**
 * Set In/Out of stock
 */
?>
<select id="product_quantity_and_stock_status"
                name="assignproduct[quantity_and_stock_status][is_in_stock]"
                title="<?php echo __('Tax Class') ?>"
                class="validate-select">
                <option value="1" <?php  ?>><?php echo __('In Stock'); ?></option>
                <option <?php ?> value="0"><?php echo __('Out of Stock'); ?></option>
            </select>
        </div>

<?php
/**
 * To add Information for Product
 * Field:information
 */
?>
    <label for="product_information" class="label"><span><?php echo __('Product Information') ?></span></label>
        <div class="control">
            <textarea id="product_description"
                name="assignproduct[description]" rows="2" cols="15"></textarea>
        </div>
 <?php
 /**
  * Submission of form
  */
 ?>
</fieldset>
<?php
/**
 * Configurable Products
 */
?>
<?php

$product = $block->getProductData ( $productId );
$nationalShippingAmount = $product->getNationalShippingAmount ();
$internationalShippingAmount = $product->getInternationalShippingAmount ();
$productTypeId = $product->getTypeId ();
if ($productTypeId == "configurable") {
 $assignProductAttributes = $block->getAssignProductAttributes ( $product );
 $usedProductAttributes = $block->getProductUsedAttributes ( $product );
 $products = $block->getAssociatedProducts ( $product );
 $associatedProducts = $products->getData ();
 ?>
<h2><?php echo __("Select the Variants");?></h2>
    <table>
        <tr>
            <th></th>
            <th><?php echo __('Price')?></th>
            <th><?php echo __('Qty')?></th>
<?php foreach($assignProductAttributes as $assignproductAttributeCode){?>
<th>
<?php echo  $assignproductAttributeCode->getProductAttribute()->getAttributeCode();?>
</th>
<?php }?>
   </tr>
<?php
 if (! empty ( $associatedProducts )) {
  foreach ( $associatedProducts as $associatedProduct ) {
   $asscprod = $block->getProductData ( $associatedProduct ['entity_id'] );
   $asscProdName = $asscprod->getName ();
   $asscProdSku = $asscprod->getSku ();
   $asscProdPrice = $asscprod->getPrice ();
   $id = $associatedProduct ['entity_id'];
   ?>
<tr>
            <td><input type="checkbox" name="variant[]" class="variant"  value="<?php echo $id;?>" /></td>
            <td><input type="text" name="price[<?php echo $id;?>]"  class="variant-price" data-validate="{required:true,'validate-greater-than-zero':true}" /></td>
            <td><input type="text" name="qty[<?php echo $id;?>]"class="variant-qty" data-validate="{required:true,'validate-greater-than-zero':true}" /></td>
   <?php foreach($usedProductAttributes as $proAttribute){?>
<td>
<?php echo $_attributeValue =$asscprod->getResource()->getAttribute($proAttribute)->getFrontend()->getValue($asscprod);?>
</td>
<?php }?>
</tr>
<?php }?>
    <?php }?>
</table>
    <script>
require([
     'jquery',
     'mage/adminhtml/wysiwyg/tiny_mce/setup'
 ], function($){
$('input:checkbox').attr('checked', 'checked');
$('input:text').attr('enabled', true);
$('td input[type="checkbox"]').change(function () {
  $(this).closest('tr').find('input[type="text"]').prop('disabled', !this.checked);
}).change();
$("#add_assign_product").submit(function(){
var checked = $("#add_assign_product input:checked").length > 0;
if (!checked){
    alert("Please check at least one Combination");
    return false;
}
});
$("#product_price").change(function(){
  $(".variant-price").val($(this).val());
});

$("#product_qty").change(function(){
  $(".variant-qty").val($(this).val());
});

});

</script>
<?php }?>

<?php
$isSellerProductShipping = $this->isSellerProductShipping ();
if ($isSellerProductShipping == 1) {
 ?>
<div>
        <label for="national_shipping_amount" class="label"><span><?php echo __('National Shipping Amount') ?></span>
        <em style="color: red; font-weight: normal; font-family: 'Open Sans', sans-serif; font-size: 12px;">*</em></label>
        <input type="text" name="national_shipping_amount" id="national_shipping_amount"
            value="<?php echo $nationalShippingAmount; ?>"title="<?php echo __('National Shipping Amount') ?>"
            class="input-text" data-validate="{required:true,'validate-greater-than-zero':true}">
    </div>
    <div>
        <label for="international_shipping_amount" class="label"><span><?php echo __('International Shipping Price') ?></span><em
            style="color: red; font-weight: normal; font-family: 'Open Sans', sans-serif; font-size: 12px;">*</em></label>
        <input type="text" name="international_shipping_amount"
            id="international_shipping_amount"
            value="<?php echo $internationalShippingAmount; ?>"
            title="<?php echo __('International Shipping Amount') ?>"
            class="input-text"
            data-validate="{required:true,'validate-greater-than-zero':true}">
    </div>
<?php  } ?>

   <div class="actions-toolbar">
        <div class="primary">
            <button id="btn_save_assign_product" type="submit"
                class="action submit primary"
                title="<?php echo __('Save') ?>">
                <span><?php echo __('Save') ?></span>
            </button>
        </div>
    </div>
</form>
<!-- Product custom option and dynamically add downloadable product data -->
<script>
require([
    'jquery',
    'mage/adminhtml/wysiwyg/tiny_mce/setup'
], function(jQ){
var config = '',
    editor;
jQ.extend(config, {settings: {
        theme_advanced_buttons1 : 'bold,italic,|,justifyleft,justifycenter,justifyright,|,',
        theme_advanced_buttons2: null,
        theme_advanced_buttons3: null,
        theme_advanced_buttons4: null,
        theme_advanced_statusbar_location: null
    },
    files_browser_window_url: false
});
editor = new tinyMceWysiwygSetup('product_description', config);
editor.turnOn();
jQ('#product_description').addClass('wysiwyg-editor').data('wysiwygEditor',  editor);
});

require([
    'jquery',
    'mage/mage'
], function($){
   var dataForm = $('#add_assign_product');
    var ignore = null;
    dataForm.mage('validation', {
            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');

});
</script>
<input type="hidden" id="sku_validate_url" name="sku_validate_url" value="<?php echo $block->getSkuValidateAjaxUrl(); ?>" />
<script>
require([
    'jquery',
    'mage/mage'
], function($){
$('.sku-update-loader').hide();
    var assigndataForm = $('#add_assign_product');
    var assignproductsku;
    var skuAvailableFlag;
    var ignore = null;
    assigndataForm.mage('validation', { ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        }).find('input:text').attr('autocomplete', 'off');
    $('#btn_save_assign_product').on('click', function(e) {
            $('#add_assign_product').submit();
    });
    var skuAvailableFlag=0;
    $('#product_sku').keyup(function(){ 
    $('.sku-update-loader').show();
        assignproductsku= $('#product_sku').val(); 
        if(assignproductsku.length!==0){
          $('#sku-error').css("display", "none");
          $('#product_sku').removeClass("mage-error");
           if(currentsku!=assignproductsku  ){    
           $.ajax({
            type: "POST",
            url: $('#sku_validate_url').val(),
            data: {sku: assignproductsku},
            success: function(transportdata){ 
                  if(transportdata==0){
                    $('.availablesku').html($('#sku_successmessage').val());   
                    $('.availablesku').css("font-size", "1.2rem"); 
                    $('.availablesku').css("color", "green");
                    $("#btn_save_assign_product").prop("disabled", false);
                    skuAvailableFlag=0; 
                   } 
                 else{
                   $('.availablesku').html($('#sku_errormessage').val()); 
                   skuAvailableFlag=1;  
                   $('.availablesku').css("color", "#e02b27");
                   $('.availablesku').css("font-size", "1.2rem"); 
                   $('#sku').addClass("mage-error");
                   } 
              $('.sku-update-loader').hide();
                  }
            });  
    }  
        }
       
     if(productsku.length==0){
     $('.sku-update-loader').hide();
     $('.availablesku').css("display", "none"); 
    } 
    else{
    $('.availablesku').css("display", "block"); 
    }                              
  });

    $("#add_assign_product").submit(function(){
            if(skuAvailableFlag == 0){
            return true;    
            }else{
            $('#product_sku').focus();    
            return false; 
            }
           
    }); 
});
</script>