<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 * */
?>
<div class="order-manage">
   <?php
   $productCollection = $block->getCollection ();
   if ($productCollection->getSize () > 0) {
    ?>
      <div class="toolbar top">
         <?php echo $block->getPagerHtml(); ?>
      </div>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history"
            id="my-orders-table">
            <caption class="table-caption"><?php echo __('Orders');?></caption>
            <tr>
                <th><?php echo __('Order #');?></th>
                <th><?php echo __('Date');?></th>

                <th><?php echo __('Product Details');?></th>
                <th><?php echo __('Total Product Amount');?></th>
                <th><?php echo __('Commission');?></th>
                <th><?php echo __('Seller Amount');?></th>
                <th><?php echo __('Status');?></th>
                <th><?php echo __('Action');?></th>
            </tr>
  <?php
    
    foreach ( $productCollection as $product ) {
     $orderId = $product->getOrderId ();
     $sellerId = $product->getSellerId ();
     $customerId = $product->getCustomerId ();
     $orderDetails = $block->getOrderDetails ( $orderId, $sellerId, $customerId );
     $getProductDetails = $block->getProductDetails ( $orderId, $sellerId );
     $createdAt = $orderDetails ['created_at'];
     $modifiedDate = new DateTime ( $createdAt );
     $createdAt = $modifiedDate->format ( 'm/d/Y' );
     $currencyCode = $product->getOrderCurrencyCode ();
     $currencySymbol = $block->getCurrencySymbol ( $currencyCode );
     if (empty ( $currencySymbol )) {
      $currencySymbol = $currencyCode;
     }
     
     ?>   
                       <tr>
                <td><?php echo $product->getIncrementId();?></td>
                <td><?php echo $createdAt;?></td>
                <td><?php echo $getProductDetails; ?></td>
                <td><?php echo $currencySymbol.number_format($product->getSellerProductTotal(), 2, '.', '');  ?></td>
                <td><?php echo $currencySymbol.number_format($product->getCommission(),2, '.', ''); ?></td>
                <td><span class="price"><?php echo $currencySymbol.number_format($product->getSellerAmount(),2,'.', '');?></span></td>
                <td><?php
    if ($product->getStatus () == 'refunded' && $orderDetails ['refund_flag'] != 1) {
      echo __ ( 'Completed' );
     } else {
      echo ucfirst ( $product->getStatus () );
     }
     ?></td>
                <td><a
                    href="<?php echo $block->getUrl('marketplace/order/vieworder/id/'.$orderId)?>"
                    class="action view"> <span><?php echo __('View');?></span>
                </a></td>
            </tr>
         <?php }?>    
      </table>
        <div class="toolbar-bottom">
            <div class="toolbar bottom">
            <?php echo $block->getPagerHtml(); ?>
         </div>
        </div>
    </div>
   <?php

} else {
    echo __ ( 'No Records were Found' );
}
?>
</div>