<?php
/**
 * Apptha
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.apptha.com/LICENSE.txt
 *
 * ==============================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * ==============================================================
 * This package designed for Magento COMMUNITY edition
 * Apptha does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Apptha does not provide extension support in case of
 * incorrect edition usage.
 * ==============================================================
 *
 * @category    Apptha
 * @package     Apptha_Marketplace
 * @version     1.2
 * @author      Apptha Team <developers@contus.in>
 * @copyright   Copyright (c) 2017 Apptha. (http://www.apptha.com)
 * @license     http://www.apptha.com/LICENSE.txt
 *
 */
?><?php
$helper = $this->helper( 'Apptha\Marketplace\Helper\Data' );
$moduleEnabledOrNot = $helper->getModuleEnable ();
if ($moduleEnabledOrNot) {
    ?>
<li class="seller-link">  
<?php
    
$websiteTitle = $this->helper ( 'Apptha\Marketplace\Helper\Data' )->getHeadTitle ();
    if (empty ( $websiteTitle )) {
        $websiteTitle = __ ( "Marketplace" );
    }
    ?>
<a <?php echo $block->getLinkAttributes() ?>><?php echo $block->escapeHtml($block->getLabel()).__($websiteTitle)?>  
     <?php echo($block->getCounter()) ? '<span class="counter qty">' . $block->escapeHtml($block->getCounter()) . '</span>' : ''; ?>  
   </a>
</li>
<?php }?>